### ISSUE TITLE
大佬可以给一个详细教程吗。谢谢了

### ISSUE THREAD

**Issue by kst1234567** [kongxiangyiren/hexo-oh-my-live2d#2]
source文件夹里放了live2d不过我是moc3的，代码复制到CHATGPT上它说没有错误，但是就是不显示我自己的自定义live2d，只显示ohmylive2d它自带的那个

**Comment by kongxiangyiren** [comment]
你可以找 [https://github.com/oh-my-live2d/oh-my-live2d](https://github.com/oh-my-live2d/oh-my-live2d) ,我是根据他改的
